name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Roda todo dia à meia-noite
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }} # Você precisará gerar um PAT (Token)
          user: vilquer
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage