uses: Platane/snk@v2
  with:github_user_name:${{ github.vilquer }}
    outputs:
      vilquer/github-snake.svg
      vilquer/github-snake-dark.svg?palette=github-dark
      vilquer/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
